theme: minima
title: Avila-Princy-M01's personal blog
description: This is where I share cool stuff about my life
author: Avila-Princy-M01
- name: Upload GitHub Pages artifact
  uses: actions/upload-pages-artifact@v3
  with:
    path: ./_site # or your build output directory
